### ISSUE TITLE
stopping people from starting and stopping

### ISSUE THREAD

**Issue by niodamian** [kibook/resourcemanager#1]
do you know if recourse manager can prevent people of using f8 to stop resources ?
also what framework u using ?

**Comment by kibook** [comment]
Players cannot stop resources in F8 unless you have enabled them to do so. They could potentially mess with NUI-based interfaces, but only in a way that affects their own client, not any other player. This resource has nothing to do with any of that though, it's meant to be a system to start/stop other resources automatically based on certain conditions, and also provides a frontend for authorized users to start/stop resources on the server manually.

I'm not sure what you mean by framework. The web UI portion is just standard HTML, CSS and Javascript so far. On my RedM server I don't use any framework like VORP or RedEM:RP, just the basic standard resources and a number of my own things like this.
